project_id = "scekmyoyodcuvadxxwmh"

[functions.api-sales]
verify_jwt = false

[functions.api-community]
verify_jwt = false

[functions.api-signals]
verify_jwt = false

[functions.daily-maintenance]
verify_jwt = false

[functions.sitemap]
verify_jwt = false